apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  name: tweet-writer
  namespace: tweet-writer
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/tweet(/|$)(.*)"
        backend:
          service:
            name: tweet-writer
            port:
              number: 8080
              