name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: latest
      project:
        description: 'Project'
        type: choice
        required: true
        options:
          - tweet_writer

env:
  version: ${{ github.event.inputs.version }}
  project: ${{ github.event.inputs.project }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
              
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -f internal/${{ env.project }}/Dockerfile -t ${{ env.project }}:${{ env.version }} .
        
      - name: Publish
        run: docker push ${{ env.project }}:${{ env.version }}
          
